---
# tasks file for jenkins
- name: "Create a dyrectory for persistent Jenkins data"
  file:
    path: /var/jenkins_data
    state: directory
    owner: nobody
    group: nobody
    mode: '0750'

- name: "Reconfigure NGINX"
  template:
    src: jenkins.conf.j2
    dest: /etc/nginx/conf.d/jenkins.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_nginx
