---
# tasks file for jenkins
#
# Here are variables for future use.
# "ansible_distribution": "Ubuntu",.
# "ansible_distribution_file_variety": "Debian",.
# "ansible_distribution_major_version": "18",.
# "ansible_distribution_release": "bionic",.
# "ansible_distribution_version": "18.04",.

- name: "Install Software if Ubuntu"
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
