---
# tasks file for jenkins
- name: "Configure Ubuntu"
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: "Configure Centos"
  include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

#- name: "Get initial Password"
#  cmd: "cat /var/jenkins_data/secrets/initialAdminPassword"
#  register: init_passwd
