---
# tasks file for jenkins
#
# Here are variables for future use.
# "ansible_distribution": "Ubuntu",.
# "ansible_distribution_file_variety": "Debian",.
# "ansible_distribution_major_version": "18",.
# "ansible_distribution_release": "bionic",.
# "ansible_distribution_version": "18.04",.

## Users ##
# nobody inside the container uid: 65534
# nobody in Ubuntu            uid: 65534
# jenkins_data in CentOS      uid: 65534 (Created by the Playbook)
#
## Groups ##
# nobody inside the container uid: 65534
# nobgroup in Ubuntu          uid: 65534
# jenkins_data in CentOS      uid: 65534 (Created by the Playbook)

- name: "Install Jenkins in Docker"
  docker_container:
    name: jenkins
    image: "jenkinsci/blueocean"
    auto_remove: no
    keep_volumes: no
    user: nobody
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

#- name: "Get initial Password"
#  cmd: "cat /var/jenkins_data/secrets/initialAdminPassword"
#  register: init_passwd

- name: "Configure Nginx if Ubuntu"
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: "Configure Nginx if Centos"
  include_tasks: centos.yml
  when: ansible_distribution == "CentOS"
