---
# tasks file for jenkins
- name: "Create a dyrectory for persistent Jenkins data"
  file:
    path: /var/jenkins_data
    state: directory
    owner: nobody
    group: nogroup
    mode: '0750'

- name: "Install Jenkins in Docker"
  docker_container:
    name: jenkins
    image: "jenkinsci/blueocean"
    auto_remove: no
    keep_volumes: no
    user: nobody
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

#- name: "Get initial Password"
#  cmd: "cat /var/jenkins_data/secrets/initialAdminPassword"
#  register: init_passwd

- name: "Reconfigure NGINX"
  template:
    src: jenkins.conf.j2
    dest: /etc/nginx/sites-available/jenkins.conf
    owner: root
    group: root
    mode: 0644

- name: "Enable new Nginx Config"
  file:
    src: /etc/nginx/sites-available/jenkins.conf
    dest: /etc/nginx/sites-enabled/jenkins.conf
    owner: root
    group: root
    state: link

- name: "Disable Defailt Nginx Config"
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart_nginx
