---
# tasks file for jenkins
- name: "Create a dyrectory for persistent Jenkins data"
  file:
    path: /var/jenkins_data
    state: directory
    owner: nobody
    group: nogroup
    mode: '0750'

- name: "Reconfigure NGINX"
  template:
    src: jenkins.conf.j2
    dest: /etc/nginx/sites-available/jenkins.conf
    owner: root
    group: root
    mode: 0644

- name: "Enable new Nginx Config"
  file:
    src: /etc/nginx/sites-available/jenkins.conf
    dest: /etc/nginx/sites-enabled/jenkins.conf
    owner: root
    group: root
    state: link

- name: "Disable Defailt Nginx Config"
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart_nginx
