---
# vars file for docker-local
docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - python3-pip
  - python-setuptools

#docker.io
