---
# vars file for docker-local
ubuntu_docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - python3-pip
  - python-setuptools

#docker.io
centos_docker_packages:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - python-pip
