---
# tasks file for docker_local
- name: "Install RPM packages, required by Docker"
  yum:
    name: "{{ centos_docker_packages }}"
    state: present

- name: "Install Python modules"
  pip:
    name: docker-py

# - name: "Check if Docker repo installed"
#   command: "ls /etc/yum.repos.d/docker-ce.repo"
#   register: docker_repo

- name: "Install Docker-CE RPM Repo"
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  # when: docker_repo.rc != 0

- name: "Install Docker-CE RPM"
  yum:
    name: docker-ce
    state: present
