---
# tasks file for docker_local
- name: "Install packages, required by docker"
  apt:
    name: "{{ docker_packages }}"
    update_cache: yes

- name: "Install Python modules"
  pip:
    name: docker-py

- name: "Install Docker-CE Repo"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: "Install Docker-CE"
  apt:
    name: docker-ce
    state: present
  when: ansible_distribution == "Ubuntu"
  # notify: docker_start

- name: "docker_start"
  systemd:
    name: docker.service
    state: started
    enabled: yes
    daemon_reload: yes
