---
# tasks file for docker_local
- name: "Install Software if Ubuntu"
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: "Install Software if CentOS"
  include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: "docker_start"
  systemd:
    name: docker.service
    state: started
    enabled: yes
    daemon_reload: yes
