---
# tasks file for docker_local
- name: "Install DEB packages, required by docker"
  apt:
    name: "{{ ubuntu_docker_packages }}"
    update_cache: yes

- name: "Install Python modules"
  pip:
    name: docker-py

- name: "Install Docker.io"
  apt:
    name: docker.io
    state: present

# - name: "Install Docker-CE DEB Repo"
#   apt_repository:
#     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
#     state: present

# - name: "Install Docker-CE Deb"
#   apt:
#     name: docker-ce
#     state: present
