---
all:
  children:
    jenkins:
      # all childrea - Ubuntu 18.04
      vars:
        ansible_become_method: sudo
        ansible_python_interpreter: /usr/bin/python3
      hosts:
        localvm:
          ansible_host: 192.168.114.107
          ansible_port: 2222
          server_fqdn: ubuntu_srv.localhost
          roles:
            - basic_utils
            - nginx
            - docker_local
            - jenkins
        jenkins_aws:
          ansible_host: 5.5.5.5
          ansible_port: 22
          server_fqdn: jks.olegk.pp.ua
          roles:
            - basic_utils
            - nginx
            - docker_local
            - jenkins
